### ISSUE TITLE
how to draw obb detection boxes, 

### ISSUE THREAD

**Issue by dhunjoshi** [dme-compunet/YoloV8#66]
I want to draw obb boxes. i tried but these are not at actual position.

**Comment by dme-compunet** [comment]
@dhunjoshi Could you please provide an example of reproduction (photo, and model if need)

**Comment by Cosmos1973GQ** [comment]
![Snipaste_2024-08-20_19-56-49](https://github.com/user-attachments/assets/e2667342-4fda-47c3-90f3-c72288120d0e)
Dear Author,

I am a student, and I have encountered some difficulties while conducting an experiment. Specifically, when I try to run the line var result = predictor.Detect(ImagePath), I receive the following error: System.InvalidOperationException: 'The loaded model does not support this task'. Initially, I thought this might be due to incompatibility issues with the ONNX file version. However, after multiple downgrades, it seems that the issue is not related to the model itself. It appears that there might be a problem with the NuGet package for Yolov8. This is because when I use the unwrapped source code shared by the author, I can successfully execute and obtain the desired results.

**Comment by dme-compunet** [comment]
@Cosmos1973GQ From the screenshot I see that you are using a model called `yolov8s_cls_seg.onnx` which I am not sure if its task is `classify` or `segment`, and with this model you are trying to perform `detect` operation - which leads to an error: `InvalidOperationException: 'The loaded model does not support this task`
